name:                ctl-edsl
version:             0.1.0.0
github:              "martinsferco/ctl-edsl"
license:             BSD-3-Clause
author:              "Martin Sferco"
maintainer:          "martinsferco.ms@gmail.com"
copyright:           "2026 Martin Sferco"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Computational Tree Logic Interpreter
# category:            Embedded Domain-Specific Language 

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/martinsferco/ctl-edsl#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - mtl
  - optparse-applicative
  - containers
  - parsec
  - graphviz
  - text
  - prettyprinter
  - prettyprinter-ansi-terminal

executables:
  ctl-edsl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ctl-edsl
    - mtl
    - optparse-applicative
    - containers
    - parsec
    - haskeline
    - exceptions

tests:
  ctl-edsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ctl-edsl
